# Generated by Django 5.2.6 on 2025-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incomeName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'income_category',
            },
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
