# Generated by Django 5.2.6 on 2025-11-10 16:14

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['is_default', 'expenseName'], 'verbose_name': 'Категория расхода', 'verbose_name_plural': 'Категории расходов'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ['is_default', 'incomeName']},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='afina.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='expenseName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='afina.incomecategory'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='incomeName',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('expenseName'), condition=models.Q(('owner__isnull', True)), name='uniq_expense_default_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('expenseName'), models.F('owner'), condition=models.Q(('owner__isnull', False)), name='uniq_expense_user_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('incomeName'), condition=models.Q(('owner__isnull', True)), name='uniq_income_default_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('incomeName'), models.F('owner'), condition=models.Q(('owner__isnull', False)), name='uniq_income_user_name_ci'),
        ),
    ]
