# Generated by Django 5.2.6 on 2025-10-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afina", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="afina.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to="afina.incomecategory",
            ),
        ),
    ]
