# Generated by Django 5.2.6 on 2025-12-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afina', '0004_savinggoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Сом (KGS)'), ('USD', 'Доллар (USD)'), ('EUR', 'Евро (EUR)')], default='KGS', max_length=3, verbose_name='Валюта'),
        ),
    ]
