# Generated by Django 5.2.6 on 2025-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afina', '0005_alter_profile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
