# Generated by Django 5.2.6 on 2025-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afina', '0007_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
